image: node:16.10.0-alpine3.14

stages:
  - build
  - build-docker
  - deploy

build:
  stage: build
  script:
    # install pnpm
    - wget -qO- https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

    # install dependencies
    - pnpm install --frozen-lockfile --prefer-offline --store-dir .pnpm-store

    # lint
    - npm run lint

    # build
    - npm run build
  cache:
    key: dependencies-${CI_COMMIT_REF_SLUG}
    paths:
      - .pnpm-store
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

build-docker:
  stage: build-docker
  image: docker:stable-git
  services:
    - docker:stable-dind
  script:
    - build
  dependencies:
    - build
  only:
    - master

deploy:
  stage: deploy
  image:
    name: totakoko/compose-deploy
    entrypoint: ['']
  script:
    - MODULES_ROOT=$PWD compose-deploy update-module spotiblind ui
  environment:
    name: production
    url: https://spotiblind.totakoko.com
  # Disable cache and previous artifacts
  cache: {}
  dependencies: []
  only:
    - master


# Adapted from https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Auto-DevOps.gitlab-ci.yml
.script_functions: &script_functions |
  [[ "$TRACE" ]] && set -x
  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE
  export CI_APPLICATION_TAG=$CI_COMMIT_SHA

  function build() {
    if [[ -n "$CI_REGISTRY_USER" ]]; then
      echo "Logging to GitLab Container Registry with CI credentials..."
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      echo ""
    fi

    if [[ -f Dockerfile ]]; then
      echo "Building Dockerfile-based application..."
      docker build --pull -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" .
      docker tag "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" "$CI_APPLICATION_REPOSITORY:latest"
    else
      echo "Missing Dockerfile!"
      exit 1
    fi

    echo "Pushing to GitLab Container Registry..."
    docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    docker push "$CI_APPLICATION_REPOSITORY:latest"
    echo ""
  }

before_script:
  - *script_functions
